### ISSUE TITLE
stackBlurImage should also accept DOM nodes instead of ID to a DOM node

### ISSUE THREAD

**Issue by mull** [flozz/StackBlur#1]
Hi

First of all thanks for an awesome library! I find it a bit weird however that the function only accepts an ID to a node. Wouldn't it make more sense if it accepted a DOM node, or perhaps both?

**Comment by flozz** [comment]
Hello,

Your talking about the `stackBlurImage` function right? :)

I modified only the two methods I needed for one of my projects to allow them to take HTML nodes as param, but I completely missed to modify `stackBlurImage`... I will update this soon ;)
