### ISSUE TITLE
Blur causes white-out

### ISSUE THREAD

**Issue by morganrallen** [flozz/StackBlur#17]
I've been working on a project using stackblur and most of the time it works as expected but some subset of images get intensely whited out even at a low blur radius. Here's an example using `canvasRGB(canvas, 0, 0, 400, 400, 2)`.

Orig
![image](https://cloud.githubusercontent.com/assets/22881/19694892/d9844ae4-9a95-11e6-88d8-643f1a35f9b8.png)

Post blur
![image](https://cloud.githubusercontent.com/assets/22881/19694903/e7afc88c-9a95-11e6-9ae7-602f23831636.png)

Any suggestions as what might be causing some images to whiteout and not others?

**Comment by flozz** [comment]
Hello,

I am not able to reproduce your issue. I made a JSFiddle: 

* https://jsfiddle.net/3zs4hycv/

**Result:**

![capture d ecran de 2016-10-26 09-48-49](https://cloud.githubusercontent.com/assets/971438/19717612/c5f6a8a6-9b61-11e6-8862-e0ed354d7480.png)


* Are you able to reproduce with the JSFiddle?
    * If yes, what is your browser and OS?
    * If no, have you set some composition operation on your canvas? Have you some code I can use to reproduce the issue?

**Comment by miranos** [comment]
I have similar issue.
Did you figured it out ?

**Comment by flozz** [comment]
Hello,

I was not able to reproduce the issue. Can you provide some code to help me reproduce this bug?

**Comment by morganrallen** [comment]
I was also never able to create a minimal test case, some processing that occurred earlier triggered this behavior, but I was never able to determine what.

**Comment by brettz9** [comment]
Without a reproducible test case, I think we should close. Feel free to open a new issue if anyone finds a case to reproduce. Thanks!
