### ISSUE TITLE
CDN hosting

### ISSUE THREAD

**Issue by morandd** [flozz/StackBlur#20]
would be awesome if you can activate GitHub Pages, start using tags for version, and publish via the CDN:
https://rawgit.com/

**Comment by flozz** [comment]
Hello,

* [there is already release tags](https://github.com/flozz/StackBlur/releases)
* I do not think this project needs Github Pages (I have to site to publish on gh pages)
* and rawgit does not seems to need I publish files on it: you just have to past the url of the files you need on it, and [this repo contains a `dist/` folder](https://github.com/flozz/StackBlur/releases) with the built files. If I try to use one with rawgit I obtain this:

https://cdn.rawgit.com/flozz/StackBlur/4ba43069/dist/stackblur.js

Regards,

**Comment by morandd** [comment]
great, thanks.

Then maybe you could add
<script src="https://cdn.rawgit.com/flozz/StackBlur/1.4.0/dist/stackblur.min.js"></script>

as an option/suggestion in the Getting Started -> Standalone Version section of the README?

I always find it easy when I can link to CDN hosted script, rather than hosting it myself. thanks!

And thanks again for this script. It's great. I've used it to assist in building 3d heatmaps:
https://github.com/morandd/aframe-heatmap3d
