### ISSUE TITLE
set souceImage equal to targetCanvas size

### ISSUE THREAD

**Issue by swust-xiaoj** [flozz/StackBlur#21]
in API `StackBlur.image(sourceImage, targetCanvas, radius, blurAlphaChannel);`.

my souceImage's size bigger than targetCanvas, and I want to set it equal to targetCanvas

can this API offered a param or some other way to solve?

thanks:)

**Comment by flozz** [comment]
Hello,

you can resize your source image first using a canvas, then you can use this
canvas as `sourceImage`. Here a quick example (I have not tested it but it
should work):

```javascript
var sourceImage = ...;   // Your source image
var targetCanvas = ...;  // Your target canvas

// Create a temporary canvas to resize the image
var resizedCanvas = document.createElement("canvas");
resizedCanvas.width = targetCanvas.width;
resizedCanvas.height = targetCanvas.height;

// Resize the image using the canvas
var ctx = resizedCanvas.getContext("2d");
ctx.drawImage(sourceImage, 0, 0, resizedCanvas.width, resizedCanvas.height);

// Blur the image
StackBlur.image(resizedCanvas, targetCanvas, 10, false);
```
:)

**Comment by swust-xiaoj** [comment]
Thanks a lot!
I have tried this way, and it worked as I expected.
thanks again for your reply and advise.
:+1:
