### ISSUE TITLE
Cannot install via bower...

### ISSUE THREAD

**Issue by PatchworkBoy** [flozz/StackBlur#25]
```
bower install stackblur-canvas
bower invalid-meta  for:/home/edudash/public_html/bower.json
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower EINVRES       Request to https://bower.herokuapp.com/packages/stackblur-canvas failed with 502
```

**Comment by flozz** [comment]
Hello,

The last line of your log suggest that it is broken on the bower side (an HTTP 502 error from bower.herokuapp.com).

Maybe it is a temporary failure and you should retry later.

Please also note that [Bower is deprecated](https://github.com/bower/bower/issues/2298) and should not be used in new projects, they recommends to use NPM or Yarn instead.

:)
