### ISSUE TITLE
Issues with Webpack compiling

### ISSUE THREAD

**Issue by hakkim** [flozz/StackBlur#30]
Hi,
I have installed the stackBlurImage using webpack. But it is not working correctly in frontend. I am getting an error says,` common.js:1307 Uncaught TypeError: stackBlurImage is not a function`. Can you please help me with this?

**Comment by brettz9** [comment]
Since 1.0, the function is exported as just`image`.

**Comment by brettz9** [comment]
Closing as my comment should have addressed.
