### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by NicolasSiver** [flozz/StackBlur#4]
Could you specify License? 
Thanks

**Comment by flozz** [comment]
Hello,

As specified [in the sources](https://github.com/flozz/StackBlur/blob/master/src/stackblur.js#L17) and in the [package.json](https://github.com/flozz/StackBlur/blob/master/package.json#L20), this lib is licensed under the [MIT license](http://opensource.org/licenses/MIT).

I will add a `LICENSE` file to the project to make things clear.
