### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by LingleDev** [flozz/StackBlur#43]
I was trying to blur an image data URI just now with StackBlur, and I got this error.

I am using Node.js v12, on a linux server

This is my code:

```js
const stack = require('stackblur-canvas')

// img is an image data uri
stack.imageDataRGB(img, 0, 0, 1081, 206, 50)
```

**Comment by flozz** [comment]
The `imageDataRGB()` function takes a canvas ([HTMLCanvasElement](https://developer.mozilla.org/fr/docs/Web/API/HTMLCanvasElement)) as first parameter, not a String.

You first have to put your data URL into an [Image](https://developer.mozilla.org/fr/docs/Web/API/HTMLImageElement/Image), and then to [draw it in a canvas](https://developer.mozilla.org/fr/docs/Web/API/CanvasRenderingContext2D/drawImage) to use this function.

**Comment by LingleDev** [comment]
ok, thank you.
