### ISSUE TITLE
Add optional WebWoker support to improve perf.

### ISSUE THREAD

**Issue by amilajack** [flozz/StackBlur#9]
Modern browsers are now allowing canvas to be rendered in a WebWorker, which will significantly increase performance of rendering.

[https://hacks.mozilla.org/2016/01/webgl-off-the-main-thread/](https://hacks.mozilla.org/2016/01/webgl-off-the-main-thread/)

**Comment by flozz** [comment]
It may be a good idea, but I have no time to implement it

**Comment by amilajack** [comment]
No worries! I'll try giving this a shot an submit a PR.

**Comment by Rickgrendel** [comment]
What is the status on this?

**Comment by flozz** [comment]
This was not implemented.
